### ISSUE TITLE
More a question than an issue...

### ISSUE THREAD

**Issue by UberGuidoZ** [jaylikesbunda/Flipper-IRDB-Search#1]
Hey there! Saw your additions and assistance on the IRDB (got them all merged - thank you!) Then I saw you had this nifty search. Hitting the github.io link redirects to https://search.flippertools.net/ which I assume is purposeful?

Would love to add this to the IRDB ReadMe so others can benefit but a few questions:

- Which link is the best link to use? Or, should this be hosted elsewhere?
- I see the DB updates by running the Python file. Is the demo link updated?

Side note: I also see the Flipper IR Formatter and will be toying with it (then likely linking it as well... is https://format.flippertools.net/ the best link?)

Greatly appreciate the assistance and contributions.

**Comment by UberGuidoZ** [comment]
Imma just use https://flippertools.net/ since it seems pretty established - and hope you continue to contribute and assist. =)

**Comment by jaylikesbunda** [comment]
> Imma just use https://flippertools.net/ since it seems pretty established - and hope you continue to contribute and assist. =)

thank you! i will make sure it's up to scratch for public use after i finish work today :)

the domain will be permanent and will add back links to formatter (once working correctly) 

also the python script just generates a .json file for the database, currently have to manually update but will be looking into more automated methods
